name: AI Smart Shoe CI-CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tahap-pengujian-ci:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Ambil Kode Terbaru
        uses: actions/checkout@v4

      - name: 2. Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install Requirements
        run: |
          pip install -r requirements.txt

      - name: 4. Jalankan Tes Rumus AI & API
        run: |
          pytest test_system.py

      - name: 5. Scan Keamanan (Security Gate)
        run: |
          bandit -r main.py

  tahap-penyebaran-cd:
    needs: tahap-pengujian-ci
    runs-on: ubuntu-latest
    steps:
      - name: 1. Ambil Kode
        uses: actions/checkout@v4

      - name: 2. Bungkus Aplikasi dengan Docker
        run: |
          docker build -t ai-smart-shoe:latest .
          echo "Docker Image Berhasil Dibuat!"

      - name: 3. Simulasi Deploy ke Pasar (Production)
        run: |
          echo "Sistem AI Smart Shoe sukses disebarkan dan siap digunakan Toko Sepatu!"